### ISSUE TITLE
Plugin install issue

### ISSUE THREAD

**Issue by fluxxus** [ismarslomic/sanity-plugin-tag-hierarchy#1]
I am having issues with installing the plugin. Installing with `npm install sanity-plugin-tag-hierarchy` says that the plugin is not found:
```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/sanity-plugin-tag-hierarchy - Not found
npm ERR! 404 
npm ERR! 404  'sanity-plugin-tag-hierarchy@*' is not in this registry.
```
I managed to install it via github http url -  `npm install sanity-plugin-tag-hierarchy@https://github.com/ismarslomic/sanity-plugin-tag-hierarchy`, but then I get the following:

![Screenshot 2023-10-11 at 17 14 09](https://github.com/ismarslomic/sanity-plugin-tag-hierarchy/assets/3802291/895ad700-1d00-4a90-93b9-9236cabcd598)

Am I missing something obvious or? 

Thx

**Comment by ismarslomic** [comment]
Thanks for showing interest for this plugin. The errors you are referring to are because this plugin was and still is in active development and the package wasn't yet published to the NPM registry. This is now resolved and I just tested that `npm install @ismarslomic/sanity-plugin-tag-hierarchy` works. Please note that README has also changed.

You are free to use and test this plugin, but its still in early development. So please expect bugs and of course help out with reporting them here.

**Comment by ismarslomic** [comment]
I have updated README with complete configuration of the Desk structure to match (updated) screenshots. Please take a look at #2
